import { readFileSync, writeFileSync, readdirSync, unlinkSync, existsSync, mkdirSync, copyFileSync } from "node:fs";
import { createHash } from "node:crypto";

// esbuild is optional — falls back to unminified if binary is wrong arch (e.g. sandbox CI)
let transform;
try {
  ({ transform } = await import("esbuild"));
  // Quick smoke-test: if the binary is the wrong arch this will throw
  await transform("1+1", { minify: true });
} catch {
  transform = null;
}

const SRC_JS = "app.src.js";
const SOURCE_PARTS = [
  "src/classification-service.js",
  "src/data-service.js",
  "src/utils.js",
  "src/photo-service.js",
  "src/main-page.js",
  "src/more-page.js",
  "src/boot.js",
];
// more.html is now a redirect stub — no hashed assets to update in it
const HTML_FILES = ["index.html", "auth-callback.html", "dashboard.html", "landing.html"];

function hashOf(buf) {
  return createHash("sha1").update(buf).digest("hex").slice(0, 10);
}

function replaceScriptSrc(html, newJsName) {
  return html.replace(/app\.[a-zA-Z0-9_-]+\.js(\?[^"']*)?/g, newJsName);
}

function replaceCssSrc(html, newCssName) {
  return html.replace(/app(\.[a-f0-9]{10})?\.css(\?[^"']*)?/g, newCssName);
}

for (const f of SOURCE_PARTS) {
  if (!existsSync(f)) {
    console.error(`Missing source part: ${f}`);
    process.exit(1);
  }
}

const bundledSource = [
  "// Generated by build.mjs. Edit src/*.js instead.",
  ...SOURCE_PARTS.map((f) => readFileSync(f, "utf8").trimEnd()),
].join("\n\n") + "\n";
writeFileSync(SRC_JS, bundledSource);

if (!existsSync(SRC_JS)) {
  console.error(`Missing generated source JS: ${SRC_JS}`);
  process.exit(1);
}

// Minify with esbuild when available; fall back to unminified for CI/sandbox
let jsBuf;
if (transform) {
  const { code: minified } = await transform(bundledSource, {
    minify: true,
    target: "es2017",
    logLevel: "silent",
  });
  jsBuf = Buffer.from(minified);
  console.log("Minified with esbuild.");
} else {
  console.warn("esbuild unavailable — outputting unminified JS (deploy on Mac for production builds).");
  jsBuf = Buffer.from(bundledSource);
}
const jsHash = hashOf(jsBuf);
const outJs = `app.${jsHash}.js`;
writeFileSync(outJs, jsBuf);

const cssBuf = readFileSync("app.css");
const cssHash = hashOf(cssBuf);
const outCss = `app.${cssHash}.css`;
writeFileSync(outCss, cssBuf);

// Update HTML to point at the new filenames
for (const f of HTML_FILES) {
  let html = readFileSync(f, "utf8");
  html = replaceScriptSrc(html, outJs);
  html = replaceCssSrc(html, outCss);
  writeFileSync(f, html);
}

// Clean up old hashed JS files
const jsFiles = readdirSync(".").filter(n => /^app\.[a-f0-9]{10}\.js$/.test(n));
for (const f of jsFiles) { if (f !== outJs) try { unlinkSync(f); } catch {} }

// Clean up old hashed CSS files
const cssFiles = readdirSync(".").filter(n => /^app\.[a-f0-9]{10}\.css$/.test(n));
for (const f of cssFiles) { if (f !== outCss) try { unlinkSync(f); } catch {} }

// ─────────────────────────────────────────────────────────────────────────────
// SW STRATEGY (industry standard — same model as production web apps):
//
//   HTML pages  → Network-first, fall back to cache for offline.
//                 HTML is NEVER served stale when online. This means the
//                 phone always loads fresh HTML that points to current hashes.
//
//   Hashed assets (app.HASH.js / app.HASH.css)
//               → Cache-first. Content-addressed = immutable. Once cached,
//                 never needs to be re-fetched. Old hashes just go unused.
//
//   Static assets (icons, manifest) → Network-first, cache for offline.
//
// This eliminates the "stale HTML → deleted CSS hash → broken app" failure
// mode permanently. HTML always comes from the network when online.
// ─────────────────────────────────────────────────────────────────────────────
writeFileSync("sw.js", `// Generated by build.mjs — do not edit directly.
// Cache names:
//   fr-assets-HASH  — immutable hashed JS/CSS (rotated each build)
//   fr-pages-v1     — HTML pages (network-first; stable name, entries replaced)
const ASSETS_CACHE = "fr-assets-${jsHash}";
const PAGES_CACHE  = "fr-pages-v1";

// Hashed asset URLs for this build
const HASHED_ASSETS = [
  "./${outJs}",
  "./${outCss}",
];

// Static assets cached for offline use (icons, manifest)
const STATIC_ASSETS = [
  "./icon-192.png",
  "./icon-512.png",
  "./manifest.webmanifest",
];

self.addEventListener("install", e => {
  e.waitUntil(
    // Pre-cache only the immutable hashed assets on install.
    // HTML is intentionally NOT pre-cached — it will be fetched fresh on first load.
    caches.open(ASSETS_CACHE).then(c => c.addAll([...HASHED_ASSETS, ...STATIC_ASSETS]))
  );
  self.skipWaiting();
});

self.addEventListener("message", e => {
  if (e.data?.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(
      keys
        // Delete ALL old fr-* caches (covers old naming "fr-{hash}" and
        // new naming "fr-assets-{hash}"). Keep current assets + pages caches.
        .filter(k => k.startsWith("fr-") && k !== ASSETS_CACHE && k !== PAGES_CACHE)
        .map(k => caches.delete(k))
    )).then(() => self.clients.claim())
  );
});

self.addEventListener("notificationclick", e => {
  e.notification.close();
  const url = e.notification.data?.url || "./";
  e.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then(wins => {
      for (const w of wins) {
        if (w.url.includes(self.registration.scope)) { w.focus(); w.navigate(url); return; }
      }
      return clients.openWindow(url);
    })
  );
});

// ── Is this URL a hashed immutable asset? ──────────────────────────────────
function isHashedAsset(url) {
  return /\\/app\\.[a-f0-9]{10}\\.(js|css)(\\?.*)?$/.test(url.pathname);
}

// ── Is this a page navigation (HTML)? ──────────────────────────────────────
function isNavigation(req, url) {
  return req.mode === "navigate"
    || url.pathname.endsWith(".html")
    || url.pathname === "/"
    || url.pathname === "";
}

self.addEventListener("fetch", e => {
  if (e.request.method !== "GET") return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;

  // ── Hashed assets: Cache-first (immutable by definition) ──────────────────
  if (isHashedAsset(url)) {
    e.respondWith(
      caches.open(ASSETS_CACHE).then(async cache => {
        const hit = await cache.match(e.request);
        if (hit) return hit;
        const res = await fetch(e.request);
        if (res.ok) cache.put(e.request, res.clone());
        return res;
      })
    );
    return;
  }

  // ── HTML pages: Network-first ──────────────────────────────────────────────
  // Always try the network. This guarantees the phone gets fresh HTML with
  // current asset hash references. Only fall back to cache when truly offline.
  if (isNavigation(e.request, url)) {
    e.respondWith(
      fetch(e.request).then(res => {
        if (res.ok) {
          caches.open(PAGES_CACHE).then(c => c.put(e.request, res.clone()));
        }
        return res;
      }).catch(async () => {
        // Offline fallback: serve cached page
        const hit = await caches.match(e.request)
          || await caches.match("./index.html");
        return hit || Response.error();
      })
    );
    return;
  }

  // ── Everything else (icons, manifest): Network-first, cache for offline ───
  e.respondWith(
    fetch(e.request).then(res => {
      if (res.ok) caches.open(ASSETS_CACHE).then(c => c.put(e.request, res.clone()));
      return res;
    }).catch(() => caches.match(e.request))
  );
});
`);

// Clean up stale hashed files in www/ before copying
if (existsSync("www")) {
  for (const f of readdirSync("www").filter(n => /^app\.[a-f0-9]{10}\.(js|css)$/.test(n))) {
    if (f !== outJs && f !== outCss) try { unlinkSync(`www/${f}`); } catch {}
  }
}

// Vendor local copies (served from capacitor://localhost — no CDN latency)
// Copied to BOTH root vendor/ (Cloudflare Pages / local dev) and www/vendor/ (Capacitor)
const VENDOR = [
  { src: "node_modules/@supabase/supabase-js/dist/umd/supabase.js", filename: "supabase.js" },
  { src: "node_modules/jspdf/dist/jspdf.umd.min.js",                filename: "jspdf.umd.min.js" },
];
mkdirSync("vendor", { recursive: true });
mkdirSync("www/vendor", { recursive: true });
for (const { src, filename } of VENDOR) {
  if (existsSync(src)) {
    copyFileSync(src, `vendor/${filename}`);
    copyFileSync(src, `www/vendor/${filename}`);
  } else {
    console.warn(`Vendor missing (run npm install): ${src}`);
  }
}

// Copy built assets to www/ for Capacitor
const WWW_ASSETS = [
  "index.html", "more.html", "auth-callback.html", "dashboard.html",
  "manifest.webmanifest", "sw.js", "app.css",
  "icon-192.png", "icon-512.png", "favicon.ico", "_redirects",
  "tos.html", "privacy.html", "landing.html",
  "robots.txt", "sitemap.xml",
];
mkdirSync("www", { recursive: true });
// Copy hashed JS + CSS
copyFileSync(outJs, `www/${outJs}`);
copyFileSync(outCss, `www/${outCss}`);
// Copy static assets
for (const f of WWW_ASSETS) {
  if (existsSync(f)) copyFileSync(f, `www/${f}`);
}
// Copy icons folder if present
if (existsSync("icons")) {
  mkdirSync("www/icons", { recursive: true });
  for (const f of readdirSync("icons")) copyFileSync(`icons/${f}`, `www/icons/${f}`);
}
console.log(`Built: ${outJs}  ${outCss}  → www/`);
