// Generated by build.mjs — do not edit directly.
// Cache names:
//   fr-assets-HASH  — immutable hashed JS/CSS (rotated each build)
//   fr-pages-v1     — HTML pages (network-first; stable name, entries replaced)
const ASSETS_CACHE = "fr-assets-5d1a609b04";
const PAGES_CACHE  = "fr-pages-v1";

// Hashed asset URLs for this build
const HASHED_ASSETS = [
  "./app.5d1a609b04.js",
  "./app.2281d8a6ba.css",
];

// Static assets cached for offline use (icons, manifest)
const STATIC_ASSETS = [
  "./icon-192.png",
  "./icon-512.png",
  "./manifest.webmanifest",
];

self.addEventListener("install", e => {
  e.waitUntil(
    // Pre-cache only the immutable hashed assets on install.
    // HTML is intentionally NOT pre-cached — it will be fetched fresh on first load.
    caches.open(ASSETS_CACHE).then(c => c.addAll([...HASHED_ASSETS, ...STATIC_ASSETS]))
  );
  self.skipWaiting();
});

self.addEventListener("message", e => {
  if (e.data?.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(
      keys
        // Delete ALL old fr-* caches (covers old naming "fr-{hash}" and
        // new naming "fr-assets-{hash}"). Keep current assets + pages caches.
        .filter(k => k.startsWith("fr-") && k !== ASSETS_CACHE && k !== PAGES_CACHE)
        .map(k => caches.delete(k))
    )).then(() => self.clients.claim())
  );
});

self.addEventListener("notificationclick", e => {
  e.notification.close();
  const url = e.notification.data?.url || "./";
  e.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then(wins => {
      for (const w of wins) {
        if (w.url.includes(self.registration.scope)) { w.focus(); w.navigate(url); return; }
      }
      return clients.openWindow(url);
    })
  );
});

// ── Is this URL a hashed immutable asset? ──────────────────────────────────
function isHashedAsset(url) {
  return /\/app\.[a-f0-9]{10}\.(js|css)(\?.*)?$/.test(url.pathname);
}

// ── Is this a page navigation (HTML)? ──────────────────────────────────────
function isNavigation(req, url) {
  return req.mode === "navigate"
    || url.pathname.endsWith(".html")
    || url.pathname === "/"
    || url.pathname === "";
}

self.addEventListener("fetch", e => {
  if (e.request.method !== "GET") return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;

  // ── Hashed assets: Cache-first (immutable by definition) ──────────────────
  if (isHashedAsset(url)) {
    e.respondWith(
      caches.open(ASSETS_CACHE).then(async cache => {
        const hit = await cache.match(e.request);
        if (hit) return hit;
        const res = await fetch(e.request);
        if (res.ok) cache.put(e.request, res.clone());
        return res;
      })
    );
    return;
  }

  // ── HTML pages: Network-first ──────────────────────────────────────────────
  // Always try the network. This guarantees the phone gets fresh HTML with
  // current asset hash references. Only fall back to cache when truly offline.
  if (isNavigation(e.request, url)) {
    e.respondWith(
      fetch(e.request).then(res => {
        if (res.ok) {
          caches.open(PAGES_CACHE).then(c => c.put(e.request, res.clone()));
        }
        return res;
      }).catch(async () => {
        // Offline fallback: serve cached page
        const hit = await caches.match(e.request)
          || await caches.match("./index.html");
        return hit || Response.error();
      })
    );
    return;
  }

  // ── Everything else (icons, manifest): Network-first, cache for offline ───
  e.respondWith(
    fetch(e.request).then(res => {
      if (res.ok) caches.open(ASSETS_CACHE).then(c => c.put(e.request, res.clone()));
      return res;
    }).catch(() => caches.match(e.request))
  );
});
